include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml

image: maven:3-jdk-8

stages:
  - build
  - deploy
  - test

build:
  stage: build
  script:
   - "mvn clean install -Dmaven.test.skip=true"
  - 'mvn deploy -s ci_settings.xml'
  artifacts:
    when: on_success
    paths:
    - target/*.jar