include:
  - template: SAST.gitlab-ci.yml
  - template: Dependency-Scanning.gitlab-ci.yml
  - template: License-Management.gitlab-ci.yml

image: maven:3-jdk-8

stages:
  - test
  - build
  - deploy

build:
  stage: build
  script:
   - "mvn clean install -Dmaven.test.skip=true"
  artifacts:
    when: on_success
    paths:
    - target/*.jar

pages:
  stage: deploy
  script:
  - 'mvn deploy -s ci_settings.xml'
  artifacts:
    paths:
    - public